### ISSUE TITLE
Kortų paėmimas į ranką nuo stalo

### ISSUE THREAD

**Issue by DovydasSp** [DovydasSp/Durak#1]
Tikslas: Patikrinti ar žaidėjui paspaudus paėmimo mygtuką, kortos nuo stalo sudedamos į žaidėjo turimų kortų kaladę.
Pradiniai reikalavimai: žaidėjas negali būti puolėjas ir ant stalo turi gulėti viena neatkirsta atakuotojo korta.
Testo scenarijus:

Užklausos tipas | Serveris + request | JSON | Kortų kiekis ant stalo | Kortų kiekis rankoje | Atsakymas kurio tikimasi
-- | -- | -- | -- | -- | --
POST | https://durakserver.azurewebsites.net/input | { “gameID” : “someid”,   “playerID” : “playerID”,   “command” : 0 } | 1 | 6 | Kortos buvusios ant stalo pridedamos prie kortų buvusių   rankoje
POST | https://durakserver.azurewebsites.net/input | { “gameID” : “someid”,   “playerID” : “playerID”,   “command” : 0 } | 3 | 6 | Kortos buvusios ant stalo pridedamos prie kortų buvusių   rankoje
POST | https://durakserver.azurewebsites.net/input | { “gameID” : “someid”,   “playerID” : “playerID”,   “command” : 0 } | 3 | 5 | Kortos buvusios ant stalo pridedamos prie kortų buvusių   rankoje
POST | https://durakserver.azurewebsites.net/input | { “gameID” : “someid”,   “playerID” : “playerID”,   “command” : 0 } | 5 | 6 | Kortos buvusios ant stalo pridedamos prie kortų buvusių   rankoje
POST | https://durakserver.azurewebsites.net/input | { “gameID” : “someid”,   “playerID” : “playerID”,   “command” : 0 } | 5 | 4 | Kortos buvusios ant stalo pridedamos prie kortų buvusių   rankoje
POST | https://durakserver.azurewebsites.net/input | Tusčias | 1 | 6 | Metama klaida

**Comment by donbur1** [comment]
Done.

**Comment by donbur1** [comment]
Closed.
